### Hello

GET http://localhost:8080/api/hello


### List employees

GET http://localhost:8080/api/employees
Accept: application/json

### Find employee by id

GET http://localhost:8080/api/employees/1
Accept: application/json

### Find employee by id (not found)

GET http://localhost:8080/api/employees/11111
Accept: application/json

### Create employee

POST http://localhost:8080/api/employees
Content-Type: application/json
Accept: application/json

{
  "name": "Jane Doe"
}

### Update employee

PUT http://localhost:8080/api/employees/1
Content-Type: application/json
Accept: application/json

{
"name": "Jack Doe 2"
}

### Create employee with empty name

POST http://localhost:8080/api/employees
Content-Type: application/json
Accept: application/json

{
  "name": ""
}


